export const products = [
  {
    title: "Nike Air max 270 Series",
    store: "Sarah Closet Store",
    description: "The new nike air max 270 series",
    rating: 4.5,
    price: 400,
    image: "/images/shoe.png",
    id: 1,
  },
  {
    title: "Nike Air max 270 Series",
    store: "Sarah Closet Store",
    description: "The new nike air max 270 series",
    rating: 4.5,
    price: 400,
    image: "/images/shoe.png",
    id: 2,
  },
  {
    title: "Nike Air max 270 Series",
    store: "Sarah Closet Store",
    description: "The new nike air max 270 series",
    rating: 4.5,
    price: 400,
    image: "/images/shoe.png",
    id: 3,
  },
  {
    title: "Nike Air max 270 Series",
    store: "Sarah Closet Store",
    description: "The new nike air max 270 series",
    rating: 4.5,
    price: 400,
    image: "/images/shoe.png",
    id: 4,
  },
  {
    title: "Nike Air max 270 Series",
    store: "Sarah Closet Store",
    description: "The new nike air max 270 series",
    rating: 4.5,
    price: 400,
    image: "/images/shoe.png",
    id: 5,
  },
  {
    title: "Nike Air max 270 Series",
    store: "Sarah Closet Store",
    description: "The new nike air max 270 series",
    rating: 4.5,
    price: 400,
    image: "/images/shoe.png",
    id: 5,
  },
  {
    title: "Nike Air max 270 Series",
    store: "Sarah Closet Store",
    description: "The new nike air max 270 series",
    rating: 4.5,
    price: 400,
    image: "/images/shoe.png",
    id: 6,
  },
  {
    title: "Nike Air max 270 Series",
    store: "Sarah Closet Store",
    description: "The new nike air max 270 series",
    rating: 4.5,
    price: 400,
    image: "/images/shoe.png",
    id: 7,
  },
];

export const productsALt = [
  {
    title: "Nike Air max 270 Series",
    store: "Sarah Closet Store",
    description: "The new nike air max 270 series",
    rating: 4.5,
    price: 400,
    image: "/images/shoe2.png",
    id: 1,
  },
  {
    title: "Nike Air max 270 Series",
    store: "Sarah Closet Store",
    description: "The new nike air max 270 series",
    rating: 4.5,
    price: 400,
    image: "/images/shoe2.png",
    id: 2,
  },
  {
    title: "Nike Air max 270 Series",
    store: "Sarah Closet Store",
    description: "The new nike air max 270 series",
    rating: 4.5,
    price: 400,
    image: "/images/shoe2.png",
    id: 3,
  },
  {
    title: "Nike Air max 270 Series",
    store: "Sarah Closet Store",
    description: "The new nike air max 270 series",
    rating: 4.5,
    price: 400,
    image: "/images/shoe2.png",
    id: 4,
  },
  {
    title: "Nike Air max 270 Series",
    store: "Sarah Closet Store",
    description: "The new nike air max 270 series",
    rating: 4.5,
    price: 400,
    image: "/images/shoe2.png",
    id: 5,
  },
  {
    title: "Nike Air max 270 Series",
    store: "Sarah Closet Store",
    description: "The new nike air max 270 series",
    rating: 4.5,
    price: 400,
    image: "/images/shoe2.png",
    id: 5,
  },
  {
    title: "Nike Air max 270 Series",
    store: "Sarah Closet Store",
    description: "The new nike air max 270 series",
    rating: 4.5,
    price: 400,
    image: "/images/shoe2.png",
    id: 6,
  },
  {
    title: "Nike Air max 270 Series",
    store: "Sarah Closet Store",
    description: "The new nike air max 270 series",
    rating: 4.5,
    price: 400,
    image: "/images/shoe2.png",
    id: 7,
  },
];
